// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ochgecxpbatowwmfjpng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jaGdlY3hwYmF0b3d3bWZqcG5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NTIzMDUsImV4cCI6MjA1ODMyODMwNX0.Xc6VYmc2n97r19svefAVrIsi07GXcNK5GvR7Ph__cuw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);